name: notepad
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  flutter_hooks: ^0.18.5+1
  fast_immutable_collections: ^7.4.1
  flutter_riverpod: ^1.0.4
  flutter_form_builder: ^7.4.0
  sqflite: ^2.0.3
  path_provider: ^2.0.11
  hooks_riverpod: ^1.0.4
  intl: ^0.17.0
  jiffy: ^5.0.0
  easy_search_bar: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

